version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: super_shoes
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/super_shoes
      JWT_SECRET: "dev-secret-change"
      UPLOAD_DIR: "/app/uploads"
      PORT: "4000"
    volumes:
      - ./api/uploads:/app/uploads
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build: ./web
    environment:
      VITE_API_URL: "http://localhost:4000"
    depends_on:
      - api
    ports:
      - "5173:5173"
    command: ["npm","run","dev","--","--host","0.0.0.0"]

volumes:
  db_data:
